### PR TITLE
Switch to pkg-check to find path to xml2 in system during build

### PR DESCRIPTION
**Pull request by jmtcsngr**

### CODE REVIEW

**Comment by keithj** [comment]
This fixes libxml2 for me. My build breaks later because we also require `libgd`:

````
cc -DHAVE_CONFIG_H -I.  -I/home/ubuntu/miniconda2/include  -std=gnu99 -Werror  -I/home/ubuntu/miniconda2/include/libxml2 -I./src -g -O2 -c -o src/src_bambi-spatial_filter.o `test -f 'src/spatial_filter.c' || echo './'`src/spatial_filter.c                                                                 
src/spatial_filter.c:36:16: fatal error: gd.h: No such file or directory    
compilation terminated.               
Makefile:1014: recipe for target 'src/src_bambi-spatial_filter.o' failed    
make[1]: *** [src/src_bambi-spatial_filter.o] Error 1                       
make[1]: Leaving directory '/home/ubuntu/bambi'                             
Makefile:740: recipe for target 'all' failed                                
make: *** [all] Error 2               
````

**Comment by jenniferliddle** [comment]
Keith - I'm happy to merge this as-is if you like, or should we wait for a libgd fix too?

**Comment by jmtcsngr** [comment]
Think this one can be replaced by #101

**Comment by jenniferliddle** [comment]
Replaced by #101

**Pull request closed without merging**
