### PR TITLE
Handle NovaseqX output

### PR DESCRIPTION
**Pull request by jenniferliddle**

### CODE REVIEW

**Comment by kjsanger** [comment]
The sam file added to the test data doesn't look like plain text (is it compressed?), unlike previous sam files in the test data. Is that expected?

**Comment by jenniferliddle** [comment]
Yes, this is expected. There are other files with a .sam extension which are actually BAM files, so this isn't unique. It isn't ideal, but it's done that way for...errr...historical reasons.

**Comment by dkj** [comment]
I think we may be best to merge with 8ca1c87 now, and release. Then address improvements for read names and qualities for further work.

**Comment by dkj** [comment]
> I think we may be best to merge with [8ca1c87](https://github.com/wtsi-npg/bambi/commit/8ca1c87d9c3aa77e7cb03f25270efe598b7dd638) now, and release. Then address improvements for read names and qualities for further work.

This merge has been done.

**Pull request closed without merging**
