### PR TITLE
Chanes for NovaSeqX

### PR DESCRIPTION
**Pull request by jenniferliddle**

### CODE REVIEW

**Comment by kjsanger** [comment]
The code looks correct to me. It would benefit from a test for the corrected read names, though.

**Comment by marcomoscasgr** [comment]
I will run the new version on the previous example run folder to check that the checksums are the same

**Comment by marcomoscasgr** [comment]
As highlighted by Keith, it will be better to have a test for it if possible to avoid testing it on our servers and keeping example folders there. 
From a first manual test of the previous example run folder, read naming and quality are now correct (details of command lines in the JIRA ticket).

**Comment by jenniferliddle** [comment]
> The code looks correct to me. It would benefit from a test for the corrected read names, though.

I'm not sure I understand this. The read names are being tested by comparing the output bam/sam files to the expected output, including read names.

**Comment by srl147** [comment]
merging for Marco as he doesn't appear to have permission to do this himself

**Pull request merged**
