### PR TITLE
Feature dual tags

### PR DESCRIPTION
**Pull request by valeriuo**
1. Added support for dual tag matching. The dual tags can be provided as a single string (i.e. AGACAGTGGTACCACG), in which case the user has to provide the index of the string where the second tag starts by using the **--dual-tag** <_position_> option (i.e. **--dual-tag 9**), or as a space separated string (i.e. AGACAGTG GTACCACG), in which case the decoder will interpret the two parts as tags, without the need for providing the **--dual-tag** option.
2. Added support for detecting "tag hops" (combinations of TAG1 from a pair and TAG2 from a different pair). Tag hops statistics are output in a separate file, <_metrics_file_name_>.hops
3. Fixed column header display issue.
4. Added unit tests.

### CODE REVIEW

**Comment by jenniferliddle** [comment]
The first thing to note, obviously, is that it fails the Travis test.

The printing of the metrics file has been tidied up considerably by lining up the columns using multiple tabs. Unfortunately there is another program that reads the metrics file, and will probably be confused by this. I forget which program this is, something in the QC suite I think. @mgcam or @dozy may know.

The index separator is assumed to be a space. Bambi i2b actually writes the separator as a hyphen, and other programs that look for separators treat any non-alpha character as a separator.

There is a minor memory leak in that next_tag has been added to the bc_details_t struct, but is not freed in the free_bcd() function.

**Comment by jenniferliddle** [comment]
Ah, ignore the memory leak comment. Just noticed that next_tag is never allocated any memory.

**Comment by jenniferliddle** [comment]
I've noticed that we are adding new entries into the barcode array with a 'tag_hop' flag, and then later extracting these entries into another array (sortedTagArray) to sort and process them.
All arrays in the current program apart from the new sortedTagArray are of type va_t and handled by functions in the array.c library.
It occurs to me that if the new tag array were created at the same time and of the same type as the barcode array, and the new entries added directly to the new array, it would give some advantages:
- there would be no need for the new 'tag_hop' field in bc_details_t
- there would be no need for the new global variable count_taghops
- there would be no need for the new tests for [if not tag_hop] when processing the barcode array
- there would be no need to perform a separate extraction of the new tags from the barcode array

**Comment by jenniferliddle** [comment]
It isn't clear why the new 'ignore_pf' flag has been added.
If this is specified, then the format of the metrics file will presumably change.
We need to be sure that this change will not effect upstream programs that read the metrics file.

**Comment by valeriuo** [comment]
There are a few aspects:

1. The new tags are created on the fly, when the alignment file is processed. They could be added to a secondary array, but then extra logic will be needed for matching the alignment entries to the secondary array, which would be boilerplate code, basically.
2. **va_t** holds an arrays of pointers to a structure. **qsort** needs an array of structures. We could implement our own sorting logic for a va_t array, given the type it holds.
3. I could get around of  having **count_taghops** as a global variable by passing it as a parameter. The more elegant solution will be to group all the global info in a separate structure and pass a pointer to that structure to all the functions which require that global info.

**Comment by jenniferliddle** [comment]
1. I don't understand about "matching the alignment entries to the secondary array". Aren't we just adding entries to the array? I'm simply suggesting adding them to a secondary array directly, rather than adding them to the barcode array and then extracting them to a separate array later.
2. qsort can be used to sort an array of pointers to structures, as easily as an array of structures. It just means one more level of indirection in the comparison function.
3. At the moment there are no global variables. I agree that if we do have some then grouping them into a structure is more elegant than not, but if possible I'd still like to avoid them all together.
By using a secondary array of type va_t then we don't need a count_taghops variable at all, because the array size is available as part of the va_t struct.

**Comment by valeriuo** [comment]
I agree that we can add the new entries to the secondary array directly and that this array can be sorted just by modifying the comparison function, but we still need the new entries in the barcode array, as well, for subsequent matches. Thus, it might be useful to have a dedicated flag that distinguishes between the original tag pairs and the new tag hops, when the barcode array is written in the metrics file.

**Comment by jenniferliddle** [comment]
Ah, of course you are right, I'd missed the "subsequent matches" bit.
I'd still like to lose the global variable, if at all possible. If we make the new array a va_t structure, doesn't that solve the problem?

**Comment by jenniferliddle** [comment]
Another thought. Why are we sorting the secondary array? We don't sort the original barcode array before printing. If we do want them sorted, why not just sort the barcode array with the new tags added? That would avoid the need for extracting the new tags into a separate array altogether.

**Comment by valeriuo** [comment]
There was only a request to sort the tag hops in descending order of the read count. If there order of the original tag pairs in the metrics file is not important, we could add them to the sorting algorithm, as well.

**Pull request merged**
